---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.16'

inputs:
  - name: dontpanic-git-repo
    path: src/code.cloudfoundry.org/dontpanic

run:
  dir: src/code.cloudfoundry.org/dontpanic
  path: ci/scripts/integration-tests.sh
  user: root
